Feat02: add workflow file

diff --git a/01-building-blocks.yaml b/01-building-blocks.yaml
--- a/01-building-blocks.yaml
+++ b/01-building-blocks.yaml
@@ -13,8 +13,8 @@ jobs:
         steps:
             - name: Failed Step
               run: |
-              echo "I will fail"
-              exit 1
+                  echo "I will fail"
+                   exit 1
 
             - name: Say goodbye
               run: echo "Goodbye"
